HW 1 PR
dunaitseva/vk_edu_web pull request #1
Opened 2022-03-19 21:07 UTC by dunaitseva

2022-03-19 22:12 UTC, Zherdev requested changes

2022-03-19 22:12 UTC, Zherdev commented on public/index.html
> +                                    <input type="hidden">
Подскажи, пожалуйста, а для чего нужен этот input ?

2022-03-19 22:12 UTC, Zherdev commented on static/css/qa-styles.css
> +}
No new line at end of file

Не супер-криминал, но лучше поправим

2022-03-19 23:00 UTC, dunaitseva commented on public/index.html
> +                                    <input type="hidden">
Я в некоторых формах планировал сразу размещать кусочки тегов, которые необходимы будут для шаблонов и django. Конкретно тут я планировал позже в инпуте разместить id вопроса, чтобы запрос с формы прилетал сразу с его id и др. аргументами. Но могу убрать, если это плохо.

2022-03-20 13:59 UTC, Zherdev commented on public/index.html
> +                                    <input type="hidden">
Ок, просто поинтересовался

2022-03-20 14:00 UTC, Zherdev approved these changes

2022-04-06 16:26 UTC, merged